name: droneio_test
version: 0.0.1
description: Lorem ipsum
author: Alejandro Garc√≠a <agarcia@maubic.es>
homepage: https://github.com/agarez/maubic
dependencies:
  browser: ">=0.4.5"
  unittest: ">=0.4.5"
  # Pin these github packages so we don't get breaks from publishing them:
  csslib: ">=0.4.3 <0.4.4"
  html5lib: ">=0.4.3 <0.4.4"

